# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "http" {
    address        = "https://gitlab.com/api/v4/projects/21268142/terraform/state/2-uat_596290292139-eu-west-1_webapp.tfstate"
    password       = "PUcofBjwmznWfWRMH6Wg"
    retry_wait_min = "5"
    username       = "username"
  }
}
